


spring:
  application:
    name: shineon_server_sys
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  rabbitmq:
    port: 5672
    addresses: 127.0.0.1
    password: matao
    username: matao

  cloud:
    stream:
      bindings:
        userinput:
#          group: user
          destination : user


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:81/eureka


server:
  port: 127