package com.shineon.coder.db.dao;

import com.shineon.coder.db.pojo.ShineonUser;

public interface ShineonUserMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Wed Sep 18 15:16:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Wed Sep 18 15:16:53 CST 2019
     */
    int insert(ShineonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Wed Sep 18 15:16:53 CST 2019
     */
    int insertSelective(ShineonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Wed Sep 18 15:16:53 CST 2019
     */
    ShineonUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Wed Sep 18 15:16:53 CST 2019
     */
    int updateByPrimaryKeySelective(ShineonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Wed Sep 18 15:16:53 CST 2019
     */
    int updateByPrimaryKey(ShineonUser record);
}