package com.shineon.coder.db.dao;

import com.shineon.coder.db.pojo.ShineonUserAttached;
import com.shineon.coder.db.pojo.ShineonUserAttachedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShineonUserAttachedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user_attached
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int countByExample(ShineonUserAttachedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user_attached
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int deleteByExample(ShineonUserAttachedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user_attached
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int insert(ShineonUserAttached record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user_attached
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int insertSelective(ShineonUserAttached record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user_attached
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    List<ShineonUserAttached> selectByExample(ShineonUserAttachedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user_attached
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShineonUserAttached record, @Param("example") ShineonUserAttachedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user_attached
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int updateByExample(@Param("record") ShineonUserAttached record, @Param("example") ShineonUserAttachedExample example);
}