package com.shineon.coder.db.dao;

import com.shineon.coder.db.pojo.ShineonUser;
import com.shineon.coder.db.pojo.ShineonUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShineonUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int countByExample(ShineonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int deleteByExample(ShineonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int insert(ShineonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int insertSelective(ShineonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    List<ShineonUser> selectByExample(ShineonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    ShineonUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShineonUser record, @Param("example") ShineonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int updateByExample(@Param("record") ShineonUser record, @Param("example") ShineonUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int updateByPrimaryKeySelective(ShineonUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbggenerated Thu Jun 20 16:36:21 CST 2019
     */
    int updateByPrimaryKey(ShineonUser record);
}