package com.shineon.coder.db.sql.pojo;

import java.util.Date;

public class RmtActiorInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.id
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.actorName
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String actorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.createTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.secretLevel
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer secretlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.description
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.showOrder
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer showorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.systemActorFlag
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String systemactorflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.reserved1
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.reserved2
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_actior_info.privilegeGroup
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String privilegegroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.id
     *
     * @return the value of rmt_actior_info.id
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.id
     *
     * @param id the value for rmt_actior_info.id
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.actorName
     *
     * @return the value of rmt_actior_info.actorName
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getActorname() {
        return actorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.actorName
     *
     * @param actorname the value for rmt_actior_info.actorName
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setActorname(String actorname) {
        this.actorname = actorname == null ? null : actorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.createTime
     *
     * @return the value of rmt_actior_info.createTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.createTime
     *
     * @param createtime the value for rmt_actior_info.createTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.secretLevel
     *
     * @return the value of rmt_actior_info.secretLevel
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getSecretlevel() {
        return secretlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.secretLevel
     *
     * @param secretlevel the value for rmt_actior_info.secretLevel
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setSecretlevel(Integer secretlevel) {
        this.secretlevel = secretlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.description
     *
     * @return the value of rmt_actior_info.description
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.description
     *
     * @param description the value for rmt_actior_info.description
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.showOrder
     *
     * @return the value of rmt_actior_info.showOrder
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.showOrder
     *
     * @param showorder the value for rmt_actior_info.showOrder
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setShoworder(Integer showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.systemActorFlag
     *
     * @return the value of rmt_actior_info.systemActorFlag
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getSystemactorflag() {
        return systemactorflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.systemActorFlag
     *
     * @param systemactorflag the value for rmt_actior_info.systemActorFlag
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setSystemactorflag(String systemactorflag) {
        this.systemactorflag = systemactorflag == null ? null : systemactorflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.reserved1
     *
     * @return the value of rmt_actior_info.reserved1
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.reserved1
     *
     * @param reserved1 the value for rmt_actior_info.reserved1
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.reserved2
     *
     * @return the value of rmt_actior_info.reserved2
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.reserved2
     *
     * @param reserved2 the value for rmt_actior_info.reserved2
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_actior_info.privilegeGroup
     *
     * @return the value of rmt_actior_info.privilegeGroup
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getPrivilegegroup() {
        return privilegegroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_actior_info.privilegeGroup
     *
     * @param privilegegroup the value for rmt_actior_info.privilegeGroup
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setPrivilegegroup(String privilegegroup) {
        this.privilegegroup = privilegegroup == null ? null : privilegegroup.trim();
    }
}