package com.shineon.coder.db.sql.pojo;

import java.util.Date;

public class RmtDepartmentChart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.departmentID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.departmentName
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.organizationName
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String organizationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.levelInfo
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String levelinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.parentID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.showOrder
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private Integer showorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.createdTime
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private Date createdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.createUserID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.modifiedTime
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private Date modifiedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.modifyUserID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String modifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.deletedTime
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private Date deletedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.deletedUserID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String deleteduserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart.deletedFlag
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private Byte deletedflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.id
     *
     * @return the value of rmt_department_chart.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.id
     *
     * @param id the value for rmt_department_chart.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.departmentID
     *
     * @return the value of rmt_department_chart.departmentID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.departmentID
     *
     * @param departmentid the value for rmt_department_chart.departmentID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.departmentName
     *
     * @return the value of rmt_department_chart.departmentName
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.departmentName
     *
     * @param departmentname the value for rmt_department_chart.departmentName
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.organizationName
     *
     * @return the value of rmt_department_chart.organizationName
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getOrganizationname() {
        return organizationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.organizationName
     *
     * @param organizationname the value for rmt_department_chart.organizationName
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setOrganizationname(String organizationname) {
        this.organizationname = organizationname == null ? null : organizationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.levelInfo
     *
     * @return the value of rmt_department_chart.levelInfo
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getLevelinfo() {
        return levelinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.levelInfo
     *
     * @param levelinfo the value for rmt_department_chart.levelInfo
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setLevelinfo(String levelinfo) {
        this.levelinfo = levelinfo == null ? null : levelinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.parentID
     *
     * @return the value of rmt_department_chart.parentID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.parentID
     *
     * @param parentid the value for rmt_department_chart.parentID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.showOrder
     *
     * @return the value of rmt_department_chart.showOrder
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public Integer getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.showOrder
     *
     * @param showorder the value for rmt_department_chart.showOrder
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setShoworder(Integer showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.createdTime
     *
     * @return the value of rmt_department_chart.createdTime
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.createdTime
     *
     * @param createdtime the value for rmt_department_chart.createdTime
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.createUserID
     *
     * @return the value of rmt_department_chart.createUserID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.createUserID
     *
     * @param createuserid the value for rmt_department_chart.createUserID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.modifiedTime
     *
     * @return the value of rmt_department_chart.modifiedTime
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public Date getModifiedtime() {
        return modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.modifiedTime
     *
     * @param modifiedtime the value for rmt_department_chart.modifiedTime
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setModifiedtime(Date modifiedtime) {
        this.modifiedtime = modifiedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.modifyUserID
     *
     * @return the value of rmt_department_chart.modifyUserID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.modifyUserID
     *
     * @param modifyuserid the value for rmt_department_chart.modifyUserID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setModifyuserid(String modifyuserid) {
        this.modifyuserid = modifyuserid == null ? null : modifyuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.deletedTime
     *
     * @return the value of rmt_department_chart.deletedTime
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public Date getDeletedtime() {
        return deletedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.deletedTime
     *
     * @param deletedtime the value for rmt_department_chart.deletedTime
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setDeletedtime(Date deletedtime) {
        this.deletedtime = deletedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.deletedUserID
     *
     * @return the value of rmt_department_chart.deletedUserID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getDeleteduserid() {
        return deleteduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.deletedUserID
     *
     * @param deleteduserid the value for rmt_department_chart.deletedUserID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setDeleteduserid(String deleteduserid) {
        this.deleteduserid = deleteduserid == null ? null : deleteduserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart.deletedFlag
     *
     * @return the value of rmt_department_chart.deletedFlag
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public Byte getDeletedflag() {
        return deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart.deletedFlag
     *
     * @param deletedflag the value for rmt_department_chart.deletedFlag
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setDeletedflag(Byte deletedflag) {
        this.deletedflag = deletedflag;
    }
}