package com.shineon.coder.db.sql.pojo;

import java.util.Date;

public class RmtDepartmentChartInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.id
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.departmentID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.departmentCode
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private Integer departmentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.departmentName
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.organizationID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String organizationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.levelInfo
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String levelinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.parentID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.showOrder
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private Integer showorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.createdTime
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private Date createdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.createUserID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.modifyTime
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.modifyUserID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String modifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.reserved1
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_chart_info.reserved2
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.id
     *
     * @return the value of rmt_department_chart_info.id
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.id
     *
     * @param id the value for rmt_department_chart_info.id
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.departmentID
     *
     * @return the value of rmt_department_chart_info.departmentID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.departmentID
     *
     * @param departmentid the value for rmt_department_chart_info.departmentID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.departmentCode
     *
     * @return the value of rmt_department_chart_info.departmentCode
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public Integer getDepartmentcode() {
        return departmentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.departmentCode
     *
     * @param departmentcode the value for rmt_department_chart_info.departmentCode
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setDepartmentcode(Integer departmentcode) {
        this.departmentcode = departmentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.departmentName
     *
     * @return the value of rmt_department_chart_info.departmentName
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.departmentName
     *
     * @param departmentname the value for rmt_department_chart_info.departmentName
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.organizationID
     *
     * @return the value of rmt_department_chart_info.organizationID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.organizationID
     *
     * @param organizationid the value for rmt_department_chart_info.organizationID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid == null ? null : organizationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.levelInfo
     *
     * @return the value of rmt_department_chart_info.levelInfo
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getLevelinfo() {
        return levelinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.levelInfo
     *
     * @param levelinfo the value for rmt_department_chart_info.levelInfo
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setLevelinfo(String levelinfo) {
        this.levelinfo = levelinfo == null ? null : levelinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.parentID
     *
     * @return the value of rmt_department_chart_info.parentID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.parentID
     *
     * @param parentid the value for rmt_department_chart_info.parentID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.showOrder
     *
     * @return the value of rmt_department_chart_info.showOrder
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public Integer getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.showOrder
     *
     * @param showorder the value for rmt_department_chart_info.showOrder
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setShoworder(Integer showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.createdTime
     *
     * @return the value of rmt_department_chart_info.createdTime
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.createdTime
     *
     * @param createdtime the value for rmt_department_chart_info.createdTime
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.createUserID
     *
     * @return the value of rmt_department_chart_info.createUserID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.createUserID
     *
     * @param createuserid the value for rmt_department_chart_info.createUserID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.modifyTime
     *
     * @return the value of rmt_department_chart_info.modifyTime
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.modifyTime
     *
     * @param modifytime the value for rmt_department_chart_info.modifyTime
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.modifyUserID
     *
     * @return the value of rmt_department_chart_info.modifyUserID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.modifyUserID
     *
     * @param modifyuserid the value for rmt_department_chart_info.modifyUserID
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setModifyuserid(String modifyuserid) {
        this.modifyuserid = modifyuserid == null ? null : modifyuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.reserved1
     *
     * @return the value of rmt_department_chart_info.reserved1
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.reserved1
     *
     * @param reserved1 the value for rmt_department_chart_info.reserved1
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_chart_info.reserved2
     *
     * @return the value of rmt_department_chart_info.reserved2
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_chart_info.reserved2
     *
     * @param reserved2 the value for rmt_department_chart_info.reserved2
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }
}