package com.shineon.coder.db.sql.pojo;

import java.util.Date;

public class RmtDepartmentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.id
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.departmentID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.departmentCode
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private Integer departmentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.departmentName
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.departmentType
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String departmenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.description
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.createdTime
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private Date createdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.createUserID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.modifyTime
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.modifyUserID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String modifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.deletedTime
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private Date deletedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.deletedUserID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String deleteduserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.deletedFlag
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private Byte deletedflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.reserved1
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_department_info.reserved2
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.id
     *
     * @return the value of rmt_department_info.id
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.id
     *
     * @param id the value for rmt_department_info.id
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.departmentID
     *
     * @return the value of rmt_department_info.departmentID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.departmentID
     *
     * @param departmentid the value for rmt_department_info.departmentID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.departmentCode
     *
     * @return the value of rmt_department_info.departmentCode
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public Integer getDepartmentcode() {
        return departmentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.departmentCode
     *
     * @param departmentcode the value for rmt_department_info.departmentCode
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setDepartmentcode(Integer departmentcode) {
        this.departmentcode = departmentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.departmentName
     *
     * @return the value of rmt_department_info.departmentName
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.departmentName
     *
     * @param departmentname the value for rmt_department_info.departmentName
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.departmentType
     *
     * @return the value of rmt_department_info.departmentType
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getDepartmenttype() {
        return departmenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.departmentType
     *
     * @param departmenttype the value for rmt_department_info.departmentType
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setDepartmenttype(String departmenttype) {
        this.departmenttype = departmenttype == null ? null : departmenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.description
     *
     * @return the value of rmt_department_info.description
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.description
     *
     * @param description the value for rmt_department_info.description
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.createdTime
     *
     * @return the value of rmt_department_info.createdTime
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.createdTime
     *
     * @param createdtime the value for rmt_department_info.createdTime
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.createUserID
     *
     * @return the value of rmt_department_info.createUserID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.createUserID
     *
     * @param createuserid the value for rmt_department_info.createUserID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.modifyTime
     *
     * @return the value of rmt_department_info.modifyTime
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.modifyTime
     *
     * @param modifytime the value for rmt_department_info.modifyTime
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.modifyUserID
     *
     * @return the value of rmt_department_info.modifyUserID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.modifyUserID
     *
     * @param modifyuserid the value for rmt_department_info.modifyUserID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setModifyuserid(String modifyuserid) {
        this.modifyuserid = modifyuserid == null ? null : modifyuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.deletedTime
     *
     * @return the value of rmt_department_info.deletedTime
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public Date getDeletedtime() {
        return deletedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.deletedTime
     *
     * @param deletedtime the value for rmt_department_info.deletedTime
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setDeletedtime(Date deletedtime) {
        this.deletedtime = deletedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.deletedUserID
     *
     * @return the value of rmt_department_info.deletedUserID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getDeleteduserid() {
        return deleteduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.deletedUserID
     *
     * @param deleteduserid the value for rmt_department_info.deletedUserID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setDeleteduserid(String deleteduserid) {
        this.deleteduserid = deleteduserid == null ? null : deleteduserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.deletedFlag
     *
     * @return the value of rmt_department_info.deletedFlag
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public Byte getDeletedflag() {
        return deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.deletedFlag
     *
     * @param deletedflag the value for rmt_department_info.deletedFlag
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setDeletedflag(Byte deletedflag) {
        this.deletedflag = deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.reserved1
     *
     * @return the value of rmt_department_info.reserved1
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.reserved1
     *
     * @param reserved1 the value for rmt_department_info.reserved1
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_department_info.reserved2
     *
     * @return the value of rmt_department_info.reserved2
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_department_info.reserved2
     *
     * @param reserved2 the value for rmt_department_info.reserved2
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }
}