package com.shineon.coder.db.sql.pojo;

public class RmtOperateGroupInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_group_info.id
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_group_info.operateGroupName
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String operategroupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_group_info.operateGroupType
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private Integer operategrouptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_group_info.belongSystem
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String belongsystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_group_info.description
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_group_info.showOrder
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private Integer showorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_group_info.reserved1
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_group_info.reserved2
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_group_info.opreateSet
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    private String opreateset;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_group_info.id
     *
     * @return the value of rmt_operate_group_info.id
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_group_info.id
     *
     * @param id the value for rmt_operate_group_info.id
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_group_info.operateGroupName
     *
     * @return the value of rmt_operate_group_info.operateGroupName
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getOperategroupname() {
        return operategroupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_group_info.operateGroupName
     *
     * @param operategroupname the value for rmt_operate_group_info.operateGroupName
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setOperategroupname(String operategroupname) {
        this.operategroupname = operategroupname == null ? null : operategroupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_group_info.operateGroupType
     *
     * @return the value of rmt_operate_group_info.operateGroupType
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public Integer getOperategrouptype() {
        return operategrouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_group_info.operateGroupType
     *
     * @param operategrouptype the value for rmt_operate_group_info.operateGroupType
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setOperategrouptype(Integer operategrouptype) {
        this.operategrouptype = operategrouptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_group_info.belongSystem
     *
     * @return the value of rmt_operate_group_info.belongSystem
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getBelongsystem() {
        return belongsystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_group_info.belongSystem
     *
     * @param belongsystem the value for rmt_operate_group_info.belongSystem
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setBelongsystem(String belongsystem) {
        this.belongsystem = belongsystem == null ? null : belongsystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_group_info.description
     *
     * @return the value of rmt_operate_group_info.description
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_group_info.description
     *
     * @param description the value for rmt_operate_group_info.description
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_group_info.showOrder
     *
     * @return the value of rmt_operate_group_info.showOrder
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public Integer getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_group_info.showOrder
     *
     * @param showorder the value for rmt_operate_group_info.showOrder
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setShoworder(Integer showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_group_info.reserved1
     *
     * @return the value of rmt_operate_group_info.reserved1
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_group_info.reserved1
     *
     * @param reserved1 the value for rmt_operate_group_info.reserved1
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_group_info.reserved2
     *
     * @return the value of rmt_operate_group_info.reserved2
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_group_info.reserved2
     *
     * @param reserved2 the value for rmt_operate_group_info.reserved2
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_group_info.opreateSet
     *
     * @return the value of rmt_operate_group_info.opreateSet
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public String getOpreateset() {
        return opreateset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_group_info.opreateSet
     *
     * @param opreateset the value for rmt_operate_group_info.opreateSet
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    public void setOpreateset(String opreateset) {
        this.opreateset = opreateset == null ? null : opreateset.trim();
    }
}