package com.shineon.coder.db.sql.pojo;

public class RmtOperateInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.id
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.operateName
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String operatename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.operateType
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer operatetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.belongSystem
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String belongsystem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.pageLocation
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String pagelocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.areaLocation
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String arealocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.applicationKey
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String applicationkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.visibility
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer visibility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.operability
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer operability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.isRequiredField
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer isrequiredfield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.description
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.reserved1
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_operate_info.reserved2
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.id
     *
     * @return the value of rmt_operate_info.id
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.id
     *
     * @param id the value for rmt_operate_info.id
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.operateName
     *
     * @return the value of rmt_operate_info.operateName
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getOperatename() {
        return operatename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.operateName
     *
     * @param operatename the value for rmt_operate_info.operateName
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setOperatename(String operatename) {
        this.operatename = operatename == null ? null : operatename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.operateType
     *
     * @return the value of rmt_operate_info.operateType
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getOperatetype() {
        return operatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.operateType
     *
     * @param operatetype the value for rmt_operate_info.operateType
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setOperatetype(Integer operatetype) {
        this.operatetype = operatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.belongSystem
     *
     * @return the value of rmt_operate_info.belongSystem
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getBelongsystem() {
        return belongsystem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.belongSystem
     *
     * @param belongsystem the value for rmt_operate_info.belongSystem
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setBelongsystem(String belongsystem) {
        this.belongsystem = belongsystem == null ? null : belongsystem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.pageLocation
     *
     * @return the value of rmt_operate_info.pageLocation
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getPagelocation() {
        return pagelocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.pageLocation
     *
     * @param pagelocation the value for rmt_operate_info.pageLocation
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setPagelocation(String pagelocation) {
        this.pagelocation = pagelocation == null ? null : pagelocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.areaLocation
     *
     * @return the value of rmt_operate_info.areaLocation
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getArealocation() {
        return arealocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.areaLocation
     *
     * @param arealocation the value for rmt_operate_info.areaLocation
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setArealocation(String arealocation) {
        this.arealocation = arealocation == null ? null : arealocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.applicationKey
     *
     * @return the value of rmt_operate_info.applicationKey
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getApplicationkey() {
        return applicationkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.applicationKey
     *
     * @param applicationkey the value for rmt_operate_info.applicationKey
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setApplicationkey(String applicationkey) {
        this.applicationkey = applicationkey == null ? null : applicationkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.visibility
     *
     * @return the value of rmt_operate_info.visibility
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.visibility
     *
     * @param visibility the value for rmt_operate_info.visibility
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setVisibility(Integer visibility) {
        this.visibility = visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.operability
     *
     * @return the value of rmt_operate_info.operability
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getOperability() {
        return operability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.operability
     *
     * @param operability the value for rmt_operate_info.operability
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setOperability(Integer operability) {
        this.operability = operability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.isRequiredField
     *
     * @return the value of rmt_operate_info.isRequiredField
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getIsrequiredfield() {
        return isrequiredfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.isRequiredField
     *
     * @param isrequiredfield the value for rmt_operate_info.isRequiredField
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setIsrequiredfield(Integer isrequiredfield) {
        this.isrequiredfield = isrequiredfield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.description
     *
     * @return the value of rmt_operate_info.description
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.description
     *
     * @param description the value for rmt_operate_info.description
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.reserved1
     *
     * @return the value of rmt_operate_info.reserved1
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.reserved1
     *
     * @param reserved1 the value for rmt_operate_info.reserved1
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_operate_info.reserved2
     *
     * @return the value of rmt_operate_info.reserved2
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_operate_info.reserved2
     *
     * @param reserved2 the value for rmt_operate_info.reserved2
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }
}