package com.shineon.coder.db.sql.pojo;

public class RmtOrganizationExtendInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_extend_info.id
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_extend_info.organizationID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String organizationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_extend_info.organizationAddress
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String organizationaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_extend_info.reserved1
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_extend_info.reserved2
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_extend_info.id
     *
     * @return the value of rmt_organization_extend_info.id
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_extend_info.id
     *
     * @param id the value for rmt_organization_extend_info.id
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_extend_info.organizationID
     *
     * @return the value of rmt_organization_extend_info.organizationID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_extend_info.organizationID
     *
     * @param organizationid the value for rmt_organization_extend_info.organizationID
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid == null ? null : organizationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_extend_info.organizationAddress
     *
     * @return the value of rmt_organization_extend_info.organizationAddress
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getOrganizationaddress() {
        return organizationaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_extend_info.organizationAddress
     *
     * @param organizationaddress the value for rmt_organization_extend_info.organizationAddress
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setOrganizationaddress(String organizationaddress) {
        this.organizationaddress = organizationaddress == null ? null : organizationaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_extend_info.reserved1
     *
     * @return the value of rmt_organization_extend_info.reserved1
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_extend_info.reserved1
     *
     * @param reserved1 the value for rmt_organization_extend_info.reserved1
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_extend_info.reserved2
     *
     * @return the value of rmt_organization_extend_info.reserved2
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_extend_info.reserved2
     *
     * @param reserved2 the value for rmt_organization_extend_info.reserved2
     *
     * @mbggenerated Mon Oct 28 16:10:59 CST 2019
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }
}