package com.shineon.coder.db.sql.pojo;

import java.util.Date;

public class RmtOrganizationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.id
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.organizationID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String organizationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.organizationCode
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer organizationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.organizationName
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String organizationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.organizationType
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer organizationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.description
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.createdTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Date createdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.createUserID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.modifyTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Date modifytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.modifyUserID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String modifyuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.deletedTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Date deletedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.deletedUserID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String deleteduserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.deletedFlag
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Byte deletedflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.reserved1
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_info.reserved2
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.id
     *
     * @return the value of rmt_organization_info.id
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.id
     *
     * @param id the value for rmt_organization_info.id
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.organizationID
     *
     * @return the value of rmt_organization_info.organizationID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.organizationID
     *
     * @param organizationid the value for rmt_organization_info.organizationID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid == null ? null : organizationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.organizationCode
     *
     * @return the value of rmt_organization_info.organizationCode
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getOrganizationcode() {
        return organizationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.organizationCode
     *
     * @param organizationcode the value for rmt_organization_info.organizationCode
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setOrganizationcode(Integer organizationcode) {
        this.organizationcode = organizationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.organizationName
     *
     * @return the value of rmt_organization_info.organizationName
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getOrganizationname() {
        return organizationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.organizationName
     *
     * @param organizationname the value for rmt_organization_info.organizationName
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setOrganizationname(String organizationname) {
        this.organizationname = organizationname == null ? null : organizationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.organizationType
     *
     * @return the value of rmt_organization_info.organizationType
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getOrganizationtype() {
        return organizationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.organizationType
     *
     * @param organizationtype the value for rmt_organization_info.organizationType
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setOrganizationtype(Integer organizationtype) {
        this.organizationtype = organizationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.description
     *
     * @return the value of rmt_organization_info.description
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.description
     *
     * @param description the value for rmt_organization_info.description
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.createdTime
     *
     * @return the value of rmt_organization_info.createdTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Date getCreatedtime() {
        return createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.createdTime
     *
     * @param createdtime the value for rmt_organization_info.createdTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.createUserID
     *
     * @return the value of rmt_organization_info.createUserID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.createUserID
     *
     * @param createuserid the value for rmt_organization_info.createUserID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.modifyTime
     *
     * @return the value of rmt_organization_info.modifyTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.modifyTime
     *
     * @param modifytime the value for rmt_organization_info.modifyTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.modifyUserID
     *
     * @return the value of rmt_organization_info.modifyUserID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getModifyuserid() {
        return modifyuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.modifyUserID
     *
     * @param modifyuserid the value for rmt_organization_info.modifyUserID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setModifyuserid(String modifyuserid) {
        this.modifyuserid = modifyuserid == null ? null : modifyuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.deletedTime
     *
     * @return the value of rmt_organization_info.deletedTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Date getDeletedtime() {
        return deletedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.deletedTime
     *
     * @param deletedtime the value for rmt_organization_info.deletedTime
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setDeletedtime(Date deletedtime) {
        this.deletedtime = deletedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.deletedUserID
     *
     * @return the value of rmt_organization_info.deletedUserID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getDeleteduserid() {
        return deleteduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.deletedUserID
     *
     * @param deleteduserid the value for rmt_organization_info.deletedUserID
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setDeleteduserid(String deleteduserid) {
        this.deleteduserid = deleteduserid == null ? null : deleteduserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.deletedFlag
     *
     * @return the value of rmt_organization_info.deletedFlag
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Byte getDeletedflag() {
        return deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.deletedFlag
     *
     * @param deletedflag the value for rmt_organization_info.deletedFlag
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setDeletedflag(Byte deletedflag) {
        this.deletedflag = deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.reserved1
     *
     * @return the value of rmt_organization_info.reserved1
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.reserved1
     *
     * @param reserved1 the value for rmt_organization_info.reserved1
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_info.reserved2
     *
     * @return the value of rmt_organization_info.reserved2
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_info.reserved2
     *
     * @param reserved2 the value for rmt_organization_info.reserved2
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }
}