package com.shineon.coder.db.sql.pojo;

public class RmtOrganizationExtend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_extend.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_extend.organizationID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String organizationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_organization_extend.organizationAddress
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String organizationaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_extend.id
     *
     * @return the value of rmt_organization_extend.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_extend.id
     *
     * @param id the value for rmt_organization_extend.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_extend.organizationID
     *
     * @return the value of rmt_organization_extend.organizationID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_extend.organizationID
     *
     * @param organizationid the value for rmt_organization_extend.organizationID
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid == null ? null : organizationid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_organization_extend.organizationAddress
     *
     * @return the value of rmt_organization_extend.organizationAddress
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getOrganizationaddress() {
        return organizationaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_organization_extend.organizationAddress
     *
     * @param organizationaddress the value for rmt_organization_extend.organizationAddress
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setOrganizationaddress(String organizationaddress) {
        this.organizationaddress = organizationaddress == null ? null : organizationaddress.trim();
    }
}