package com.shineon.coder.db.sql.pojo;

public class RmtPrivilegeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_privilege_info.id
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_privilege_info.privilegeName
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    private String privilegename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_privilege_info.description
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_privilege_info.showOrder
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    private Integer showorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_privilege_info.reserved1
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_privilege_info.reserved2
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    private String reserved2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_privilege_info.operateGroup
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    private String operategroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_privilege_info.id
     *
     * @return the value of rmt_privilege_info.id
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_privilege_info.id
     *
     * @param id the value for rmt_privilege_info.id
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_privilege_info.privilegeName
     *
     * @return the value of rmt_privilege_info.privilegeName
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public String getPrivilegename() {
        return privilegename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_privilege_info.privilegeName
     *
     * @param privilegename the value for rmt_privilege_info.privilegeName
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public void setPrivilegename(String privilegename) {
        this.privilegename = privilegename == null ? null : privilegename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_privilege_info.description
     *
     * @return the value of rmt_privilege_info.description
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_privilege_info.description
     *
     * @param description the value for rmt_privilege_info.description
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_privilege_info.showOrder
     *
     * @return the value of rmt_privilege_info.showOrder
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public Integer getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_privilege_info.showOrder
     *
     * @param showorder the value for rmt_privilege_info.showOrder
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public void setShoworder(Integer showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_privilege_info.reserved1
     *
     * @return the value of rmt_privilege_info.reserved1
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_privilege_info.reserved1
     *
     * @param reserved1 the value for rmt_privilege_info.reserved1
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_privilege_info.reserved2
     *
     * @return the value of rmt_privilege_info.reserved2
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_privilege_info.reserved2
     *
     * @param reserved2 the value for rmt_privilege_info.reserved2
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_privilege_info.operateGroup
     *
     * @return the value of rmt_privilege_info.operateGroup
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public String getOperategroup() {
        return operategroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_privilege_info.operateGroup
     *
     * @param operategroup the value for rmt_privilege_info.operateGroup
     *
     * @mbggenerated Mon Dec 16 17:06:58 CST 2019
     */
    public void setOperategroup(String operategroup) {
        this.operategroup = operategroup == null ? null : operategroup.trim();
    }
}