package com.shineon.coder.db.sql.pojo;

public class RmtUserExtendInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.id
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.userID
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.realName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.spellName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String spellname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.postName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String postname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.dutiesName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String dutiesname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.officeAddress
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String officeaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.mobilePhone
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String mobilephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.officeTelephone
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String officetelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.email
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.officeCode
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String officecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.description
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.reserved1
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private Integer reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_extend_info.reserved2
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.id
     *
     * @return the value of rmt_user_extend_info.id
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.id
     *
     * @param id the value for rmt_user_extend_info.id
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.userID
     *
     * @return the value of rmt_user_extend_info.userID
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.userID
     *
     * @param userid the value for rmt_user_extend_info.userID
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.realName
     *
     * @return the value of rmt_user_extend_info.realName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.realName
     *
     * @param realname the value for rmt_user_extend_info.realName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.spellName
     *
     * @return the value of rmt_user_extend_info.spellName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getSpellname() {
        return spellname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.spellName
     *
     * @param spellname the value for rmt_user_extend_info.spellName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setSpellname(String spellname) {
        this.spellname = spellname == null ? null : spellname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.postName
     *
     * @return the value of rmt_user_extend_info.postName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getPostname() {
        return postname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.postName
     *
     * @param postname the value for rmt_user_extend_info.postName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setPostname(String postname) {
        this.postname = postname == null ? null : postname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.dutiesName
     *
     * @return the value of rmt_user_extend_info.dutiesName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getDutiesname() {
        return dutiesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.dutiesName
     *
     * @param dutiesname the value for rmt_user_extend_info.dutiesName
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setDutiesname(String dutiesname) {
        this.dutiesname = dutiesname == null ? null : dutiesname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.officeAddress
     *
     * @return the value of rmt_user_extend_info.officeAddress
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getOfficeaddress() {
        return officeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.officeAddress
     *
     * @param officeaddress the value for rmt_user_extend_info.officeAddress
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setOfficeaddress(String officeaddress) {
        this.officeaddress = officeaddress == null ? null : officeaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.mobilePhone
     *
     * @return the value of rmt_user_extend_info.mobilePhone
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.mobilePhone
     *
     * @param mobilephone the value for rmt_user_extend_info.mobilePhone
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.officeTelephone
     *
     * @return the value of rmt_user_extend_info.officeTelephone
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getOfficetelephone() {
        return officetelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.officeTelephone
     *
     * @param officetelephone the value for rmt_user_extend_info.officeTelephone
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setOfficetelephone(String officetelephone) {
        this.officetelephone = officetelephone == null ? null : officetelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.email
     *
     * @return the value of rmt_user_extend_info.email
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.email
     *
     * @param email the value for rmt_user_extend_info.email
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.officeCode
     *
     * @return the value of rmt_user_extend_info.officeCode
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getOfficecode() {
        return officecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.officeCode
     *
     * @param officecode the value for rmt_user_extend_info.officeCode
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setOfficecode(String officecode) {
        this.officecode = officecode == null ? null : officecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.description
     *
     * @return the value of rmt_user_extend_info.description
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.description
     *
     * @param description the value for rmt_user_extend_info.description
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.reserved1
     *
     * @return the value of rmt_user_extend_info.reserved1
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public Integer getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.reserved1
     *
     * @param reserved1 the value for rmt_user_extend_info.reserved1
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setReserved1(Integer reserved1) {
        this.reserved1 = reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_extend_info.reserved2
     *
     * @return the value of rmt_user_extend_info.reserved2
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_extend_info.reserved2
     *
     * @param reserved2 the value for rmt_user_extend_info.reserved2
     *
     * @mbggenerated Mon Dec 02 11:28:06 CST 2019
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }
}