package com.shineon.coder.db.sql.pojo;

import java.util.Date;

public class RmtUserActorInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.id
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.userID
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.departmentID
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.actorGroup
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private String actorgroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.speciallyGroup
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private String speciallygroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.createTime
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.createUserID
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private String createuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.description
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.reserved1
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private String reserved1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_actor_info.reserved2
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    private String reserved2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.id
     *
     * @return the value of rmt_user_actor_info.id
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.id
     *
     * @param id the value for rmt_user_actor_info.id
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.userID
     *
     * @return the value of rmt_user_actor_info.userID
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.userID
     *
     * @param userid the value for rmt_user_actor_info.userID
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.departmentID
     *
     * @return the value of rmt_user_actor_info.departmentID
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.departmentID
     *
     * @param departmentid the value for rmt_user_actor_info.departmentID
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.actorGroup
     *
     * @return the value of rmt_user_actor_info.actorGroup
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public String getActorgroup() {
        return actorgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.actorGroup
     *
     * @param actorgroup the value for rmt_user_actor_info.actorGroup
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setActorgroup(String actorgroup) {
        this.actorgroup = actorgroup == null ? null : actorgroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.speciallyGroup
     *
     * @return the value of rmt_user_actor_info.speciallyGroup
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public String getSpeciallygroup() {
        return speciallygroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.speciallyGroup
     *
     * @param speciallygroup the value for rmt_user_actor_info.speciallyGroup
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setSpeciallygroup(String speciallygroup) {
        this.speciallygroup = speciallygroup == null ? null : speciallygroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.createTime
     *
     * @return the value of rmt_user_actor_info.createTime
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.createTime
     *
     * @param createtime the value for rmt_user_actor_info.createTime
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.createUserID
     *
     * @return the value of rmt_user_actor_info.createUserID
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.createUserID
     *
     * @param createuserid the value for rmt_user_actor_info.createUserID
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setCreateuserid(String createuserid) {
        this.createuserid = createuserid == null ? null : createuserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.description
     *
     * @return the value of rmt_user_actor_info.description
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.description
     *
     * @param description the value for rmt_user_actor_info.description
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.reserved1
     *
     * @return the value of rmt_user_actor_info.reserved1
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public String getReserved1() {
        return reserved1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.reserved1
     *
     * @param reserved1 the value for rmt_user_actor_info.reserved1
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setReserved1(String reserved1) {
        this.reserved1 = reserved1 == null ? null : reserved1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_actor_info.reserved2
     *
     * @return the value of rmt_user_actor_info.reserved2
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public String getReserved2() {
        return reserved2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_actor_info.reserved2
     *
     * @param reserved2 the value for rmt_user_actor_info.reserved2
     *
     * @mbggenerated Mon Dec 23 17:15:18 CST 2019
     */
    public void setReserved2(String reserved2) {
        this.reserved2 = reserved2 == null ? null : reserved2.trim();
    }
}