package com.shineon.coder.db.sql.pojo;

import java.util.Date;

public class RmtUserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_login.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_login.userId
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_login.LoginIP
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String loginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_login.LastTimeLogin
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private Date lasttimelogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_login.LastTimeLogout
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private Integer lasttimelogout;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_login.id
     *
     * @return the value of rmt_user_login.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_login.id
     *
     * @param id the value for rmt_user_login.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_login.userId
     *
     * @return the value of rmt_user_login.userId
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_login.userId
     *
     * @param userid the value for rmt_user_login.userId
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_login.LoginIP
     *
     * @return the value of rmt_user_login.LoginIP
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_login.LoginIP
     *
     * @param loginip the value for rmt_user_login.LoginIP
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip == null ? null : loginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_login.LastTimeLogin
     *
     * @return the value of rmt_user_login.LastTimeLogin
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public Date getLasttimelogin() {
        return lasttimelogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_login.LastTimeLogin
     *
     * @param lasttimelogin the value for rmt_user_login.LastTimeLogin
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setLasttimelogin(Date lasttimelogin) {
        this.lasttimelogin = lasttimelogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_login.LastTimeLogout
     *
     * @return the value of rmt_user_login.LastTimeLogout
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public Integer getLasttimelogout() {
        return lasttimelogout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_login.LastTimeLogout
     *
     * @param lasttimelogout the value for rmt_user_login.LastTimeLogout
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setLasttimelogout(Integer lasttimelogout) {
        this.lasttimelogout = lasttimelogout;
    }
}