package com.shineon.coder.db.sql.pojo;

public class RmtUserDepartment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_department.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_department.userId
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_department.departmentId
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private String departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rmt_user_department.showOrder
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    private Integer showorder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_department.id
     *
     * @return the value of rmt_user_department.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_department.id
     *
     * @param id the value for rmt_user_department.id
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_department.userId
     *
     * @return the value of rmt_user_department.userId
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_department.userId
     *
     * @param userid the value for rmt_user_department.userId
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_department.departmentId
     *
     * @return the value of rmt_user_department.departmentId
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public String getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_department.departmentId
     *
     * @param departmentid the value for rmt_user_department.departmentId
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid == null ? null : departmentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rmt_user_department.showOrder
     *
     * @return the value of rmt_user_department.showOrder
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public Integer getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rmt_user_department.showOrder
     *
     * @param showorder the value for rmt_user_department.showOrder
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    public void setShoworder(Integer showorder) {
        this.showorder = showorder;
    }
}