spring:
  cloud:
    stream:
      bindings:
        UserNoticeMessageOutput:
          destination: UserNoticeMessage
        UserNoticeMessageInput:
          destination: UserNoticeMessage
  application:
    name: shineon.base.user
  rabbitmq:
    addresses: 127.0.0.1
    password: matao
    publisherconfirms: true
    port: 5672
    username: matao
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
server:
  port: 122
eureka:
  client:
    serviceurl:
      defaultZone: "http://127.0.0.1:81/eureka"

ribbon:
  ConnectTimeout: 4000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  ReadTimeout: 8000   #负载均衡超时时间，默认值5000
logging:
  level:
    root: info
  file: log/shineon.base.user.log
feign:
  hystrix:
    enabled: true