server:
  port: 182


eureka:
  client:
    service-url:
      defaultZone: http://10.0.192.104:81/eureka


zuul:
  routes:
    uauth-api:
      path: /uauth/**
      service-id :  shineon.api.uauth
      sensitiveHeaders: "*"
    web-page:
      path: /page/**
      service-id:  shineon.web.usr
      sensitiveHeaders: "*"
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
ribbon:
  ReadTimeout: 3000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 1000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1



spring:
  application:
    name: shineon.zuul
  session:
    store-type: redis
    timeout: 3600s
    redis:
      flush-mode: immediate
      namespace:
        spring: session

  redis:
    host: 10.0.127.235
    port: 6379
