spring: 
  cloud: 
    stream: 
      bindings:
        MataoMessageOutput: 
          destination: MataoMessage
        MataoMessageInput: 
          destination: MataoMessage
  application: 
    name: shineon-api-uauth
  rabbitmq: 
    addresses: 127.0.0.1
    password: matao
    publisherconfirms: true
    port: 5672
    username: matao
  session: 
    timeout: 3600s
    redis: 
      namespace: 
        spring: session
      flushmode: on_save
    storetype: redis
  servlet: 
    multipart: 
      resolvelazily: true
      maxrequestsize: 6000MB
      location: "c:/tmp"
      filesizethreshold: 2000
      maxfilesize: 6000MB
  redis: 
    host: 127.0.0.1
    port: 6379
    database: 0
server: 
  port: 129
eureka: 
  client: 
    serviceurl: 
      defaultZone: "http://127.0.0.1:81/eureka"

feign:
  hystrix:
    enabled: true
logging:
  file: log/shineon-api-uauth.log
  level:
    root : info

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false  #是否所有操作都重试

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: trace,beans,env,mappings,metrics
