spring: 
  cloud: 
    stream: 
      bindings:
        MataoMessageOutput: 
          destination: MataoMessage
        MataoMessageInput: 
          destination: MataoMessage
  application: 
    name: shineon_api_uauth
  rabbitmq: 
    addresses: 127.0.0.1
    password: matao
    publisherconfirms: true
    port: 5672
    username: matao
  session: 
    timeout: 3600s
    redis: 
      namespace: 
        spring: session
      flushmode: on_save
    storetype: redis
  servlet: 
    multipart: 
      resolvelazily: true
      maxrequestsize: 6000MB
      location: "c:/tmp"
      filesizethreshold: 2000
      maxfilesize: 6000MB
  redis: 
    host: 10.0.192.104
    port: 6379
    database: 0
server: 
  port: 129
eureka: 
  client: 
    serviceurl: 
      defaultZone: "http://10.0.192.104:81/eureka"