spring:
  application:
    name: shineon-db-user
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: shineon@1234
    url: jdbc:mysql://127.0.0.1:3306/mg_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: matao_test


mybatis:
  mapper-locations: classpath:com/shineon/coder/db/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:81/eureka


server:
  port: 121

shineon:
  version: 20190724

logging:
  file: log/shineon-api-uauth.log
  level:
    root : info

