spring: 
  cloud: 
    stream: 
      rabbit: 
        bindings: 
          PrivilegeMessageInput: 
            consumer: 
              deadLetterQueueName: UserErrorMessage.errorMessage
              autoBindDlq: true
              deadLetterExchange: UserErrorMessage
          UserNoticeMessageInput: 
            consumer: 
              deadLetterQueueName: UserErrorMessage.errorMessage
              autoBindDlq: true
              deadLetterExchange: UserErrorMessage
          UserNoticeMessageOutput: 
            producer: 
              deadLetterQueueName: UserErrorMessage.errorMessage
              autoBindDlq: true
              deadLetterExchange: UserErrorMessage
      bindings: 
        Matao3MessageInput: 
          destination: Matao3Message
        Matao3MessageOutput: 
          destination: Matao3Message
        PrivilegeMessageOutput: 
          destination: PrivilegeMessage
        UserNoticeMessageOutput: 
          destination: UserNoticeMessage
        PrivilegeMessageInput: 
          destination: PrivilegeMessage
          group: privilege
        UserErrorMessageInput: 
          destination: UserErrorMessage
          group: errorMessage
        UserNoticeMessageInput: 
          destination: UserNoticeMessage
          group: userNotice
  main: 
    allow-bean-definition-overriding: true
  application: 
    name: shineon.base.user
  rabbitmq: 
    addresses: 127.0.0.1
    password: matao
    port: 5672
    username: matao
  redis: 
    host: 127.0.0.1
    port: 6379
    database: 0
ribbon: 
  ConnectTimeout: 4000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  ReadTimeout: 8000   #负载均衡超时时间，默认值5000
server: 
  port: 125
logging: 
  level: 
    root: info
  file: log/shineon.base.user.log
feign: 
  hystrix: 
    enabled: true
eureka: 
  client: 
    serviceurl: 
      defaultZone: "http://127.0.0.1:81/eureka"
  instance: 
    prefer-ip-address: true