server:
  port: 81

eureka:
  client:
    service-url:
      defaultZone: "http://127.0.0.1:82/eureka"
    register-with-eureka: true
    fetch-registry: true


spring:
  application:
    name: shineon-eurake
