spring: 
  cloud: 
    stream: 
      bindings: 
        useroutput: 
          destination: usermatao
        userinput: 
          destination: usermatao
        Matao2MessageOutput: 
          destination: Matao2Message
        Matao2MessageInput: 
          destination: Matao2Message
  application: 
    name: shineon-server-uauth
  rabbitmq: 
    addresses: 127.0.0.1
    password: matao
    publisherconfirms: true
    port: 5672
    username: matao
  redis: 
    host: 127.0.0.1
    port: 6379
    database: 0
server: 
  port: 122
logging: 
  level: 
    root: info
  file: log/shineonapiuauth.log
feign: 
  hystrix: 
    enabled: true
eureka: 
  client: 
    serviceurl: 
      defaultZone: "http://127.0.0.1:81/eureka"
mybatis: 
  mapperlocations: "classpath:com/shineon/coder/db/mapper/*.xml"

ribbon:
  ReadTimeout: 8000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 4000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1
