package com.shineon.coder.db.sql.dao;

import com.shineon.coder.db.sql.pojo.RmtDepartmentChart;

public interface RmtDepartmentChartMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insert(RmtDepartmentChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insertSelective(RmtDepartmentChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    RmtDepartmentChart selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKeySelective(RmtDepartmentChart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_department_chart
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKey(RmtDepartmentChart record);
}