package com.shineon.coder.db.sql.dao;

import com.shineon.coder.db.sql.pojo.RmtOrganizationExtend;

public interface RmtOrganizationExtendMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insert(RmtOrganizationExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insertSelective(RmtOrganizationExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    RmtOrganizationExtend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKeySelective(RmtOrganizationExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKey(RmtOrganizationExtend record);
}