package com.shineon.coder.db.sql.dao;

import com.shineon.coder.db.sql.pojo.RmtOperateGroup;

public interface RmtOperateGroupMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_operate_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_operate_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insert(RmtOperateGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_operate_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insertSelective(RmtOperateGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_operate_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    RmtOperateGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_operate_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKeySelective(RmtOperateGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_operate_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(RmtOperateGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_operate_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKey(RmtOperateGroup record);
}