package com.shineon.coder.db.sql.dao;

import com.shineon.coder.db.sql.pojo.RmtOrganizationExtendInfo;

public interface RmtOrganizationExtendInfoMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int insert(RmtOrganizationExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int insertSelective(RmtOrganizationExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    RmtOrganizationExtendInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int updateByPrimaryKeySelective(RmtOrganizationExtendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_organization_extend_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int updateByPrimaryKey(RmtOrganizationExtendInfo record);
}