package com.shineon.coder.db.sql.dao;

import com.shineon.coder.db.sql.pojo.RmtPrivilegeGroupInfo;

public interface RmtPrivilegeGroupInfoMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int insert(RmtPrivilegeGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int insertSelective(RmtPrivilegeGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    RmtPrivilegeGroupInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int updateByPrimaryKeySelective(RmtPrivilegeGroupInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group_info
     *
     * @mbggenerated Thu Jan 02 15:35:06 CST 2020
     */
    int updateByPrimaryKey(RmtPrivilegeGroupInfo record);
}