package com.shineon.coder.db.sql.dao;

import com.shineon.coder.db.sql.pojo.RmtPrivilegeGroup;

public interface RmtPrivilegeGroupMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insert(RmtPrivilegeGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insertSelective(RmtPrivilegeGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    RmtPrivilegeGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKeySelective(RmtPrivilegeGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(RmtPrivilegeGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_privilege_group
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKey(RmtPrivilegeGroup record);
}