package com.shineon.coder.db.sql.dao;

import com.shineon.coder.db.sql.pojo.RmtUserDepartmentInfo;

public interface RmtUserDepartmentInfoMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    int insert(RmtUserDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    int insertSelective(RmtUserDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    RmtUserDepartmentInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    int updateByPrimaryKeySelective(RmtUserDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department_info
     *
     * @mbggenerated Fri Dec 20 14:44:36 CST 2019
     */
    int updateByPrimaryKey(RmtUserDepartmentInfo record);
}