package com.shineon.coder.db.sql.dao;

import com.shineon.coder.db.sql.pojo.RmtUserExtend;

public interface RmtUserExtendMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insert(RmtUserExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insertSelective(RmtUserExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    RmtUserExtend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKeySelective(RmtUserExtend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_extend
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKey(RmtUserExtend record);
}