package com.shineon.coder.db.sql.dao;

import com.shineon.coder.db.sql.pojo.RmtUserDepartment;

public interface RmtUserDepartmentMapperBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insert(RmtUserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int insertSelective(RmtUserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    RmtUserDepartment selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKeySelective(RmtUserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rmt_user_department
     *
     * @mbggenerated Wed Oct 23 14:59:54 CST 2019
     */
    int updateByPrimaryKey(RmtUserDepartment record);
}