package com.mg.coder.db.dao;

import com.mg.coder.db.pojo.MgBaseUser;
import java.util.List;

public interface MgBaseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_user
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_user
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    int insert(MgBaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_user
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    MgBaseUser selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_user
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    List<MgBaseUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_user
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    int updateByPrimaryKey(MgBaseUser record);
}