package com.mg.coder.db.dao;

import com.mg.coder.db.pojo.MgBaseRegion;
import java.util.List;

public interface MgBaseRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_region
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    int deleteByPrimaryKey(Long rgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_region
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    int insert(MgBaseRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_region
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    MgBaseRegion selectByPrimaryKey(Long rgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_region
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    List<MgBaseRegion> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mg_base_region
     *
     * @mbggenerated Wed Aug 28 17:11:15 CST 2019
     */
    int updateByPrimaryKey(MgBaseRegion record);
}