package com.shineon.coder.db.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ShineonUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public ShineonUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andDisplaynameIsNull() {
            addCriterion("displayName is null");
            return (Criteria) this;
        }

        public Criteria andDisplaynameIsNotNull() {
            addCriterion("displayName is not null");
            return (Criteria) this;
        }

        public Criteria andDisplaynameEqualTo(String value) {
            addCriterion("displayName =", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotEqualTo(String value) {
            addCriterion("displayName <>", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameGreaterThan(String value) {
            addCriterion("displayName >", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameGreaterThanOrEqualTo(String value) {
            addCriterion("displayName >=", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameLessThan(String value) {
            addCriterion("displayName <", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameLessThanOrEqualTo(String value) {
            addCriterion("displayName <=", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameLike(String value) {
            addCriterion("displayName like", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotLike(String value) {
            addCriterion("displayName not like", value, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameIn(List<String> values) {
            addCriterion("displayName in", values, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotIn(List<String> values) {
            addCriterion("displayName not in", values, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameBetween(String value1, String value2) {
            addCriterion("displayName between", value1, value2, "displayname");
            return (Criteria) this;
        }

        public Criteria andDisplaynameNotBetween(String value1, String value2) {
            addCriterion("displayName not between", value1, value2, "displayname");
            return (Criteria) this;
        }

        public Criteria andParentIsNull() {
            addCriterion("parent is null");
            return (Criteria) this;
        }

        public Criteria andParentIsNotNull() {
            addCriterion("parent is not null");
            return (Criteria) this;
        }

        public Criteria andParentEqualTo(Integer value) {
            addCriterion("parent =", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotEqualTo(Integer value) {
            addCriterion("parent <>", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThan(Integer value) {
            addCriterion("parent >", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent >=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThan(Integer value) {
            addCriterion("parent <", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentLessThanOrEqualTo(Integer value) {
            addCriterion("parent <=", value, "parent");
            return (Criteria) this;
        }

        public Criteria andParentIn(List<Integer> values) {
            addCriterion("parent in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotIn(List<Integer> values) {
            addCriterion("parent not in", values, "parent");
            return (Criteria) this;
        }

        public Criteria andParentBetween(Integer value1, Integer value2) {
            addCriterion("parent between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andParentNotBetween(Integer value1, Integer value2) {
            addCriterion("parent not between", value1, value2, "parent");
            return (Criteria) this;
        }

        public Criteria andUsercodeIsNull() {
            addCriterion("usercode is null");
            return (Criteria) this;
        }

        public Criteria andUsercodeIsNotNull() {
            addCriterion("usercode is not null");
            return (Criteria) this;
        }

        public Criteria andUsercodeEqualTo(String value) {
            addCriterion("usercode =", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotEqualTo(String value) {
            addCriterion("usercode <>", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeGreaterThan(String value) {
            addCriterion("usercode >", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeGreaterThanOrEqualTo(String value) {
            addCriterion("usercode >=", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLessThan(String value) {
            addCriterion("usercode <", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLessThanOrEqualTo(String value) {
            addCriterion("usercode <=", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeLike(String value) {
            addCriterion("usercode like", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotLike(String value) {
            addCriterion("usercode not like", value, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeIn(List<String> values) {
            addCriterion("usercode in", values, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotIn(List<String> values) {
            addCriterion("usercode not in", values, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeBetween(String value1, String value2) {
            addCriterion("usercode between", value1, value2, "usercode");
            return (Criteria) this;
        }

        public Criteria andUsercodeNotBetween(String value1, String value2) {
            addCriterion("usercode not between", value1, value2, "usercode");
            return (Criteria) this;
        }

        public Criteria andUserthumbIsNull() {
            addCriterion("userthumb is null");
            return (Criteria) this;
        }

        public Criteria andUserthumbIsNotNull() {
            addCriterion("userthumb is not null");
            return (Criteria) this;
        }

        public Criteria andUserthumbEqualTo(String value) {
            addCriterion("userthumb =", value, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbNotEqualTo(String value) {
            addCriterion("userthumb <>", value, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbGreaterThan(String value) {
            addCriterion("userthumb >", value, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbGreaterThanOrEqualTo(String value) {
            addCriterion("userthumb >=", value, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbLessThan(String value) {
            addCriterion("userthumb <", value, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbLessThanOrEqualTo(String value) {
            addCriterion("userthumb <=", value, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbLike(String value) {
            addCriterion("userthumb like", value, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbNotLike(String value) {
            addCriterion("userthumb not like", value, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbIn(List<String> values) {
            addCriterion("userthumb in", values, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbNotIn(List<String> values) {
            addCriterion("userthumb not in", values, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbBetween(String value1, String value2) {
            addCriterion("userthumb between", value1, value2, "userthumb");
            return (Criteria) this;
        }

        public Criteria andUserthumbNotBetween(String value1, String value2) {
            addCriterion("userthumb not between", value1, value2, "userthumb");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNull() {
            addCriterion("telephone is null");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNotNull() {
            addCriterion("telephone is not null");
            return (Criteria) this;
        }

        public Criteria andTelephoneEqualTo(String value) {
            addCriterion("telephone =", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotEqualTo(String value) {
            addCriterion("telephone <>", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThan(String value) {
            addCriterion("telephone >", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("telephone >=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThan(String value) {
            addCriterion("telephone <", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThanOrEqualTo(String value) {
            addCriterion("telephone <=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLike(String value) {
            addCriterion("telephone like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotLike(String value) {
            addCriterion("telephone not like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneIn(List<String> values) {
            addCriterion("telephone in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotIn(List<String> values) {
            addCriterion("telephone not in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneBetween(String value1, String value2) {
            addCriterion("telephone between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotBetween(String value1, String value2) {
            addCriterion("telephone not between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andUsermarkIsNull() {
            addCriterion("usermark is null");
            return (Criteria) this;
        }

        public Criteria andUsermarkIsNotNull() {
            addCriterion("usermark is not null");
            return (Criteria) this;
        }

        public Criteria andUsermarkEqualTo(String value) {
            addCriterion("usermark =", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkNotEqualTo(String value) {
            addCriterion("usermark <>", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkGreaterThan(String value) {
            addCriterion("usermark >", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkGreaterThanOrEqualTo(String value) {
            addCriterion("usermark >=", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkLessThan(String value) {
            addCriterion("usermark <", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkLessThanOrEqualTo(String value) {
            addCriterion("usermark <=", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkLike(String value) {
            addCriterion("usermark like", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkNotLike(String value) {
            addCriterion("usermark not like", value, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkIn(List<String> values) {
            addCriterion("usermark in", values, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkNotIn(List<String> values) {
            addCriterion("usermark not in", values, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkBetween(String value1, String value2) {
            addCriterion("usermark between", value1, value2, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsermarkNotBetween(String value1, String value2) {
            addCriterion("usermark not between", value1, value2, "usermark");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNull() {
            addCriterion("userType is null");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNotNull() {
            addCriterion("userType is not null");
            return (Criteria) this;
        }

        public Criteria andUsertypeEqualTo(Byte value) {
            addCriterion("userType =", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotEqualTo(Byte value) {
            addCriterion("userType <>", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThan(Byte value) {
            addCriterion("userType >", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("userType >=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThan(Byte value) {
            addCriterion("userType <", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThanOrEqualTo(Byte value) {
            addCriterion("userType <=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeIn(List<Byte> values) {
            addCriterion("userType in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotIn(List<Byte> values) {
            addCriterion("userType not in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeBetween(Byte value1, Byte value2) {
            addCriterion("userType between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotBetween(Byte value1, Byte value2) {
            addCriterion("userType not between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andAdminIsNull() {
            addCriterion("admin is null");
            return (Criteria) this;
        }

        public Criteria andAdminIsNotNull() {
            addCriterion("admin is not null");
            return (Criteria) this;
        }

        public Criteria andAdminEqualTo(Byte value) {
            addCriterion("admin =", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotEqualTo(Byte value) {
            addCriterion("admin <>", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThan(Byte value) {
            addCriterion("admin >", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThanOrEqualTo(Byte value) {
            addCriterion("admin >=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThan(Byte value) {
            addCriterion("admin <", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThanOrEqualTo(Byte value) {
            addCriterion("admin <=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminIn(List<Byte> values) {
            addCriterion("admin in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotIn(List<Byte> values) {
            addCriterion("admin not in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminBetween(Byte value1, Byte value2) {
            addCriterion("admin between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotBetween(Byte value1, Byte value2) {
            addCriterion("admin not between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andTimecreatedIsNull() {
            addCriterion("timeCreated is null");
            return (Criteria) this;
        }

        public Criteria andTimecreatedIsNotNull() {
            addCriterion("timeCreated is not null");
            return (Criteria) this;
        }

        public Criteria andTimecreatedEqualTo(Date value) {
            addCriterion("timeCreated =", value, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimecreatedNotEqualTo(Date value) {
            addCriterion("timeCreated <>", value, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimecreatedGreaterThan(Date value) {
            addCriterion("timeCreated >", value, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimecreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("timeCreated >=", value, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimecreatedLessThan(Date value) {
            addCriterion("timeCreated <", value, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimecreatedLessThanOrEqualTo(Date value) {
            addCriterion("timeCreated <=", value, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimecreatedIn(List<Date> values) {
            addCriterion("timeCreated in", values, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimecreatedNotIn(List<Date> values) {
            addCriterion("timeCreated not in", values, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimecreatedBetween(Date value1, Date value2) {
            addCriterion("timeCreated between", value1, value2, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimecreatedNotBetween(Date value1, Date value2) {
            addCriterion("timeCreated not between", value1, value2, "timecreated");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedIsNull() {
            addCriterion("timeModified is null");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedIsNotNull() {
            addCriterion("timeModified is not null");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedEqualTo(Date value) {
            addCriterion("timeModified =", value, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedNotEqualTo(Date value) {
            addCriterion("timeModified <>", value, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedGreaterThan(Date value) {
            addCriterion("timeModified >", value, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("timeModified >=", value, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedLessThan(Date value) {
            addCriterion("timeModified <", value, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedLessThanOrEqualTo(Date value) {
            addCriterion("timeModified <=", value, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedIn(List<Date> values) {
            addCriterion("timeModified in", values, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedNotIn(List<Date> values) {
            addCriterion("timeModified not in", values, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedBetween(Date value1, Date value2) {
            addCriterion("timeModified between", value1, value2, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimemodifiedNotBetween(Date value1, Date value2) {
            addCriterion("timeModified not between", value1, value2, "timemodified");
            return (Criteria) this;
        }

        public Criteria andTimedeletedIsNull() {
            addCriterion("timeDeleted is null");
            return (Criteria) this;
        }

        public Criteria andTimedeletedIsNotNull() {
            addCriterion("timeDeleted is not null");
            return (Criteria) this;
        }

        public Criteria andTimedeletedEqualTo(Date value) {
            addCriterion("timeDeleted =", value, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andTimedeletedNotEqualTo(Date value) {
            addCriterion("timeDeleted <>", value, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andTimedeletedGreaterThan(Date value) {
            addCriterion("timeDeleted >", value, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andTimedeletedGreaterThanOrEqualTo(Date value) {
            addCriterion("timeDeleted >=", value, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andTimedeletedLessThan(Date value) {
            addCriterion("timeDeleted <", value, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andTimedeletedLessThanOrEqualTo(Date value) {
            addCriterion("timeDeleted <=", value, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andTimedeletedIn(List<Date> values) {
            addCriterion("timeDeleted in", values, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andTimedeletedNotIn(List<Date> values) {
            addCriterion("timeDeleted not in", values, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andTimedeletedBetween(Date value1, Date value2) {
            addCriterion("timeDeleted between", value1, value2, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andTimedeletedNotBetween(Date value1, Date value2) {
            addCriterion("timeDeleted not between", value1, value2, "timedeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedIsNull() {
            addCriterion("flagDeleted is null");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedIsNotNull() {
            addCriterion("flagDeleted is not null");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedEqualTo(Byte value) {
            addCriterion("flagDeleted =", value, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedNotEqualTo(Byte value) {
            addCriterion("flagDeleted <>", value, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedGreaterThan(Byte value) {
            addCriterion("flagDeleted >", value, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("flagDeleted >=", value, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedLessThan(Byte value) {
            addCriterion("flagDeleted <", value, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedLessThanOrEqualTo(Byte value) {
            addCriterion("flagDeleted <=", value, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedIn(List<Byte> values) {
            addCriterion("flagDeleted in", values, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedNotIn(List<Byte> values) {
            addCriterion("flagDeleted not in", values, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedBetween(Byte value1, Byte value2) {
            addCriterion("flagDeleted between", value1, value2, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andFlagdeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("flagDeleted not between", value1, value2, "flagdeleted");
            return (Criteria) this;
        }

        public Criteria andTimelimitIsNull() {
            addCriterion("timeLimit is null");
            return (Criteria) this;
        }

        public Criteria andTimelimitIsNotNull() {
            addCriterion("timeLimit is not null");
            return (Criteria) this;
        }

        public Criteria andTimelimitEqualTo(Date value) {
            addCriterion("timeLimit =", value, "timelimit");
            return (Criteria) this;
        }

        public Criteria andTimelimitNotEqualTo(Date value) {
            addCriterion("timeLimit <>", value, "timelimit");
            return (Criteria) this;
        }

        public Criteria andTimelimitGreaterThan(Date value) {
            addCriterion("timeLimit >", value, "timelimit");
            return (Criteria) this;
        }

        public Criteria andTimelimitGreaterThanOrEqualTo(Date value) {
            addCriterion("timeLimit >=", value, "timelimit");
            return (Criteria) this;
        }

        public Criteria andTimelimitLessThan(Date value) {
            addCriterion("timeLimit <", value, "timelimit");
            return (Criteria) this;
        }

        public Criteria andTimelimitLessThanOrEqualTo(Date value) {
            addCriterion("timeLimit <=", value, "timelimit");
            return (Criteria) this;
        }

        public Criteria andTimelimitIn(List<Date> values) {
            addCriterion("timeLimit in", values, "timelimit");
            return (Criteria) this;
        }

        public Criteria andTimelimitNotIn(List<Date> values) {
            addCriterion("timeLimit not in", values, "timelimit");
            return (Criteria) this;
        }

        public Criteria andTimelimitBetween(Date value1, Date value2) {
            addCriterion("timeLimit between", value1, value2, "timelimit");
            return (Criteria) this;
        }

        public Criteria andTimelimitNotBetween(Date value1, Date value2) {
            addCriterion("timeLimit not between", value1, value2, "timelimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitIsNull() {
            addCriterion("countLimit is null");
            return (Criteria) this;
        }

        public Criteria andCountlimitIsNotNull() {
            addCriterion("countLimit is not null");
            return (Criteria) this;
        }

        public Criteria andCountlimitEqualTo(Byte value) {
            addCriterion("countLimit =", value, "countlimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitNotEqualTo(Byte value) {
            addCriterion("countLimit <>", value, "countlimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitGreaterThan(Byte value) {
            addCriterion("countLimit >", value, "countlimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitGreaterThanOrEqualTo(Byte value) {
            addCriterion("countLimit >=", value, "countlimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitLessThan(Byte value) {
            addCriterion("countLimit <", value, "countlimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitLessThanOrEqualTo(Byte value) {
            addCriterion("countLimit <=", value, "countlimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitIn(List<Byte> values) {
            addCriterion("countLimit in", values, "countlimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitNotIn(List<Byte> values) {
            addCriterion("countLimit not in", values, "countlimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitBetween(Byte value1, Byte value2) {
            addCriterion("countLimit between", value1, value2, "countlimit");
            return (Criteria) this;
        }

        public Criteria andCountlimitNotBetween(Byte value1, Byte value2) {
            addCriterion("countLimit not between", value1, value2, "countlimit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shineon_user
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 18 15:00:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shineon_user
     *
     * @mbg.generated Thu Jul 18 15:00:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}